Add favourites to move items type.
aeon0/d4lf pull request #332
Opened 2024-06-28 16:54 UTC by suchyindustries

2024-06-28 17:12 UTC, cjshrader commented
I'm not sure what the use case is for this, but at the same time I don't see how more options hurt anyone.

Can you put the enum in alphabetical order? I know @chrisoro likes to keep it that way to make them easier to read (so put favorites after everything).

Also could you update the readme with this new option?

2024-06-28 17:42 UTC, cjshrader requested changes

2024-06-28 17:42 UTC, cjshrader commented on src/config/models.py
>      everything = enum.auto()
Move favorites down one more, it should be after everything to keep it alphabetical. I'd do it myself but I don't think I can

2024-06-28 17:44 UTC, cjshrader approved these changes

2024-06-28 17:44 UTC, cjshrader commented
this looks good to me, but I don't have final approval of course.

2024-06-28 17:49 UTC, suchyindustries commented
> I'm not sure what the use case is for this, but at the same time I don't see how more options hurt anyone.
> 
> Can you put the enum in alphabetical order? I know @chrisoro likes to keep it that way to make them easier to read (so put favorites after everything).
> 
> Also could you update the readme with this new option?

Personally, I missed favourites option from start of this feature. Move junk to inventory (to sell or salvage), and move favourites to stash (keep them for market or alt)

2024-06-28 18:24 UTC, chrisoro submitted a review, later dismissed

2024-06-29 08:47 UTC, chrisoro approved these changes

2024-06-29 08:48 UTC, merged